### ISSUE TITLE
Grafana persistence

### ISSUE THREAD

**Issue by nandantumu** [mlab-upenn/cea-os#21]
Let's configure grafana with bind mounts or some solution that allows people who clone and run this repo to see a quality dashboard from the jump!

**Comment by nandantumu** [comment]
See [https://grafana.com/docs/grafana/latest/administration/configure-docker/](https://grafana.com/docs/grafana/latest/administration/configure-docker/) for details on paths that Grafana uses.

**Comment by sarahbytes** [comment]
Got the bind mount working! Tested it out on another machine and the dashboards I made spun up at first launch. I'll send a pull request tomorrow once I make the AiCU dashboard look prettier - I'll remake the one we used for the poster.

**Comment by sarahbytes** [comment]
Grafana log-in credentials:

- username: admin
- pw: cea-OS_2021 

(please ignore the current dashboards in there.. I'll finish recreating the AiCU dash tomorrow)
