### ISSUE TITLE
Encode images for InfluxDB storage

### ISSUE THREAD

**Issue by sarahbytes** [mlab-upenn/cea-os#23]
I'll work on encoding images captured by our cameras to base64 (plaintext string format). We can send this text string to InfluxDB through our logger interface. 

My plan is to create a module with an image class (unless there's an existing script I should directly add this to). The class would have a member variable for the filename of the image, as well as member functions to encode and decode the image data. 

Is this on the right path? Then I think the next issue would be to display these images on Grafana.

**Comment by nandantumu** [comment]
I think within the code, the best approach would be to create a separate Logger to handle image classes, or a modified Sensor to do the encoding.
